#!/bin/sh

if test -a VERSION ; then
	VERSION="$(cat VERSION)"

	cd ..
	tar czvf pipepanic-$VERSION-$(date +%Y%m%d-%H%M%S)-backup.tar.gz pipepanic-$VERSION/
else
	echo "ERROR: File \"VERSION\" not found. This is a text file with the version number inside it."
fi
