#!/bin/bash

#This builds an ipk for the Zaurus.
#NOTE: This is run when executing 'make -f Makefile.arm'.

if test -a VERSION ; then
	VERSION="$(cat VERSION)"

	mkdir ipk
	mkdir ipk/CONTROL
	mkdir ipk/opt
	mkdir ipk/opt/QtPalmtop
	mkdir ipk/opt/QtPalmtop/apps
	mkdir ipk/opt/QtPalmtop/apps/Games
	mkdir ipk/opt/QtPalmtop/bin
	mkdir ipk/opt/QtPalmtop/pics
	mkdir ipk/opt/QtPalmtop/share
	mkdir ipk/opt/QtPalmtop/share/pipepanic
	
	cp zaurus/control ipk/CONTROL/
	cp zaurus/pipepanic.desktop ipk/opt/QtPalmtop/apps/Games/
	cp zaurus/pipepanic.png ipk/opt/QtPalmtop/pics/
	cp pipepanic zaurus/runpipepanic ipk/opt/QtPalmtop/bin/
	cp ascii15.bmp ascii30.bmp digits24.bmp digits48.bmp tiles24.bmp tiles48.bmp ipk/opt/QtPalmtop/share/pipepanic/
	
	zaurus/_ipkg-build ipk
	
	rm -rf ipk

	echo "All done."
else
	echo "ERROR: File \"VERSION\" not found. This is a text file with the version number inside it."
fi
